# Generated by Django 4.2 on 2023-06-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_message_board_content_board_create_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="board",
            old_name="delete_at",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="board",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
