# Generated by Django 4.2.2 on 2023-06-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_board_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["-created_at"]},
        ),
    ]
