# Generated by Django 4.2.2 on 2023-06-26 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "main_category",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recipient_name", models.CharField(max_length=50)),
                ("recipient_address", models.CharField(max_length=50)),
                ("recipient_phone", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "recipient",
            },
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender_name", models.CharField(max_length=50)),
                ("sender_address", models.CharField(max_length=50)),
                ("sender_phone", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sender",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.maincategory",
                    ),
                ),
            ],
            options={
                "db_table": "sub_category",
            },
        ),
        migrations.CreateModel(
            name="DocumentForm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.subcategory",
                    ),
                ),
            ],
            options={
                "db_table": "document_form",
            },
        ),
        migrations.CreateModel(
            name="DocumentChat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.maincategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_chat",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=3000)),
                ("file_path", models.CharField(max_length=1000, null=True)),
                ("title", models.CharField(max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.subcategory",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doc.recipient"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doc.sender"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document",
            },
        ),
    ]
