# Generated by Django 4.2.2 on 2023-06-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='contents',
        ),
    ]
