# Generated by Django 4.2.2 on 2023-07-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_rename_content_document_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sender',
            name='sender_address',
            field=models.CharField(max_length=100),
        ),
    ]
